version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: hunt
    ports:
      - 5432:5432/tcp
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080/tcp
  backend:
    image: hunt:latest
    container_name: hunt_backend
    build: hunt
    env_file:
      - base.env
    ports:
      - 8000:8000/tcp
    depends_on:
      - db
      - queue
  frontend:
    image: hunt_frontend:latest
    container_name: hunt_frontend
    build: hunt_frontend
    env_file:
      - base.env
    ports:
      - 8001:8001/tcp
    depends_on:
      - backend
  proxy:
    container_name: project_proxy
    build: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend


