# Generated by Django 3.1.6 on 2021-02-22 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_reward_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='picture',
        ),
    ]
