# Generated by Django 3.1.5 on 2021-02-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='verified',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
