# Generated by Django 3.1.5 on 2021-01-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='unique',
            field=models.BooleanField(default=True),
        ),
    ]
