# Generated by Django 3.1.5 on 2021-01-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210118_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='verified',
        ),
    ]
