# Generated by Django 3.1.5 on 2021-02-04 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_achievement_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='verified',
        ),
    ]
