# Generated by Django 3.1.5 on 2021-02-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_achievement_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='verified',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
