# Generated by Django 3.1.6 on 2021-02-22 22:48

from django.db import migrations, models
import hunt.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_reward_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='picture',
            field=models.FileField(blank=True, default=None, null=True, storage=hunt.storage_backends.MediaStorage(), upload_to=''),
        ),
    ]
