# Generated by Django 3.1.5 on 2021-02-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20210206_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='verified',
        ),
        migrations.AddField(
            model_name='award',
            name='verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
