# Generated by Django 3.1.6 on 2021-02-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.challenge'),
        ),
        migrations.AlterField(
            model_name='award',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.player'),
        ),
        migrations.AlterField(
            model_name='award',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.reward'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.challenge'),
        ),
    ]
